import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { App, NavBar, Sidebar, Container, Text, Col, Row, Button } from '@sui/core';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Shit UI</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <App theme={{}}>
        <Container relative fullScreen background='#0e1012'>
          <Container header>
            <NavBar></NavBar>
          </Container>

          <Sidebar absolute></Sidebar>
          <Container main pa='10em'>
            <Container section>
              <Row vertical>
                <Col>
                  <Text
                    size={theme => theme.spacing?.[18]}
                    h1
                    gradient='linear-gradient(to right, #fa709a 0%, #fee140 100%)'>
                    最了解开发者的
                  </Text>
                </Col>
                <Col>
                  <Text white size={theme => theme.spacing?.[18]} h3>
                    UI 工具库
                  </Text>
                </Col>
                <Col>
                  <Text pa='1em' px='3em' color='#566171' size={theme => theme.spacing?.[10]} p>
                    基于世界上最流行的框架 React 和现代快速的 CSS 方案
                    Emotion，创造出最美观又实用的组件，并且，任何地方都可以由你自己改写！
                  </Text>
                </Col>
                <Col pa='1em'>
                  <Button css={{color:'black'}} color='linear-gradient(to right, #fa709a 0%, #fee140 100%)'>Get Started</Button>
                </Col>
              </Row>
            </Container>
            <Container section>
              <Row vertical>
                <Col>1</Col>
              </Row>
            </Container>
            <Container section>
              {' '}
              <Row vertical>
                <Col>2</Col>
              </Row>
            </Container>
            <Container section>
              {' '}
              <Row vertical>
                <Col>3</Col>
              </Row>
            </Container>
            <Container section>
              {' '}
              <Row vertical>
                <Col>4</Col>
              </Row>
            </Container>
          </Container>
          <Container footer></Container>
        </Container>
      </App>
    </>
  );
}
