import Head from 'next/head';
import { Inter } from 'next/font/google';

import { App, Sidebar, Container, Text, Col, Row, Button, Switch, Popover } from '@sui/core';
import { useEffect, useState } from 'react';
import Image from 'next/image';
import Footer from './Footer';
import Navbar from './Navbar';
const inter = Inter({ subsets: ['latin'] });

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Shit UI</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {children}
    </>
  );
}
